### ISSUE TITLE
FEATURE: Add the ability to manually enter the duration

### ISSUE THREAD

**Issue by kostasx** [sayinmehmet47/Pomodoro-Clock#1]
It would be nice to be able to change the duration by entering the numbers directly into the number boxes instead of clicking the up/arrow buttons.

**Comment by sayinmehmet47** [comment]
I can also add a input area to add duration manually. 

![Screenshot_1](https://user-images.githubusercontent.com/75525090/118806710-1326d900-b8b0-11eb-855f-d4fb3a717876.png)

**Comment by sayinmehmet47** [comment]
Clicking to times will enable you to add a duration

**Comment by sayinmehmet47** [comment]
with buttons it looks nicer I think

**Comment by sayinmehmet47** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/75525090/118808315-102ce800-b8b2-11eb-86f5-c4b307e6f04a.png)
like you answered in stackoverflow:)))

**Comment by kostasx** [comment]
Yes, buttons along with manual input would be the perfect combination.

**Comment by sayinmehmet47** [comment]
can you check it.I added double click event

**Comment by kostasx** [comment]
Issue: When I double click the first time, it does nothing. It only gets editable after the 2nd double click. This is during the first page loading.

**Comment by sayinmehmet47** [comment]
double click issue solved
